name:       bot
version:    0.1.0
github:     "tellnobody1/bot"
license:    MIT
author:     "tellnobody1"
maintainer: "support@apple.com"
copyright:  "2021 tellnobody1"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- network-run
- network
- utf8-string
- stringsearch

executables:
  my-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
